### ISSUE TITLE
Windows releases' .pdb files have invalid names

### ISSUE THREAD

**Issue by touilleMan** [Calinou/godot-debug-builds#1]
Hi @Calinou,

First thank you for those builds, I find them pretty useful for debugging ;-)

I've noticed visual studio complains abou the name of the .pdb file and cannot load debug symbols. This is probably due to the fact the godot binary has been compiled then renamed, if I rename the .pdb file to `godot.windows.tools.64.pdb` it works fine

**Comment by Calinou** [comment]
Crap, I thought Visual Studio picked `<executable name>.pdb` automatically…

I would have preferred if I could rename the compiled executable, so you can extract multiple ZIPs alongside and not have clashing versions. I'll change the file structure so the ZIP contains a folder with non-renamed executables inside.

**Comment by Calinou** [comment]
I uploaded fixed 3.2.1 binaries and new 3.2.2 binaries that shouldn't have this problem anymore. I just left their default name as-is.
